apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.service.name }}-config'
  namespace: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
{{ if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{ end }}
data:
  config.yml: |
  {{ .Files.Get "config.yml" | b64enc | indent 2 }}
